#!/usr/bin/env bash
# Keeps a PID file and reacts to SIGTERM, SIGINT and SIGQUIT
pidfile="/var/run/myscript.pid"
echo "$$" > "$pidfile"
trap 'echo "I hate the kill command"; rm -f "$pidfile"; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$pidfile"; exit' SIGQUIT
while true
do
  echo "To infinity and beyond"
  sleep 2 &
  wait $!
done
